### ISSUE TITLE
VPN/Proxy Checking

### ISSUE THREAD

**Issue by MaxTCodes** [imAETHER/Verifier#1]
Hi, I'm just curious why would you check when the user makes the get request ([main.go:346](https://github.com/imAETHER/Verifier/blob/main/main.go#L346)), and not in the validation part (post request)? And what are the design ideas if there is a VPN/Proxy detected?

**Comment by imAETHER** [comment]
At the time when I wrote the comment I didn't know where and how the captcha/vpn detection would be implemented.
I just had that comment there to remind myself on what comes next and doesn't mean the checks will be in that spot.

The idea of having an VPN/Proxy detection is (in the future) to prevent alt accounts that were previously banned in a server from joining back (or at least make it more difficult) & to reduce the chance of bots from joining

**Comment by MaxTCodes** [comment]
In https://github.com/MaxTCodes/Verifier I added a basic VPN/Proxy check using some public API, I'll make a pull request right now if you want that added... (I haven't tested it, but it looks like it all works. I'm at school and they block discord so I can run the bot)
